name: mernstack
description: A new Flutter application.

version: 2.0.0+2

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  percent_indicator: "^2.1.1"
  http: any
  share: any
  toast: any
  shared_preferences: any
  launch_review: any
  url_launcher: any
  connectivity: any
  animated_text_kit: any
  flutter_launcher_icons: any
#  firebase_admob: any

#  showcaseview: any



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/


flutter_icons:
  image_path: "assets/icons/launch.png"
  image_path_ios: "assets/icons/launch.png"
  android: true
  ios: true
  adaptive_icon_background: "assets/icons/launch.png"
  adaptive_icon_foreground: "assets/icons/launch.png"
  #  run flutter packages pub run flutter_launcher_icons:main
